### Transmitter Metadata
GET {{transmitterConfigUrl}}

### List receiver
GET {{issuer}}/ssf/management/receivers
Authorization: Bearer {{keycloakToken}}

### Get receiver
GET {{issuer}}/ssf/management/receivers/{{receiverAlias}}
Authorization: Bearer {{keycloakToken}}

### Register receiver with managed stream (POLL)
PUT {{issuer}}/ssf/management/receivers/{{receiverAlias}}
Authorization: Bearer {{keycloakToken}}
Accept: application/json
Content-Type: application/json

{
  "description": "Keycloak Demo Receiver",
  "transmitterUrl": "{{transmitterUrl}}",
  "transmitterAccessToken": "{{transmitterToken}}",
  "transmitterConfigUrl": "{{transmitterConfigUrl}}",
  "deliveryMethod": "urn:ietf:rfc:8936",
  "managedStream": true,
  "pollIntervalSeconds": 10,
  "eventsRequested": [
    "https://schemas.openid.net/secevent/caep/event-type/session-revoked",
    "https://schemas.openid.net/secevent/caep/event-type/token-claims-change",
    "https://schemas.openid.net/secevent/caep/event-type/assurance-level-change",
    "https://schemas.openid.net/secevent/caep/event-type/device-compliance-change",
    "https://schemas.openid.net/secevent/caep/event-type/credential-change"
  ],
  "pushAuthorizationToken": "{{pushToken}}"
}

### Register receiver with unmanaged stream (POLL)
PUT {{issuer}}/ssf/management/receivers/{{receiverAlias}}
Authorization: Bearer {{keycloakToken}}
Accept: application/json
Content-Type: application/json

{
  "transmitterUrl": "{{transmitterUrl}}",
  "transmitterAccessToken": "{{transmitterToken}}",
  "transmitterConfigUrl": "{{transmitterConfigUrl}}",
  "streamId": "30682283-bf37-4916-bf73-6cc3b51b0e51",
  "managedStream": false,
  "pollIntervalSeconds": 10
}

### Register receiver with unmanaged stream (PUSH)
PUT {{issuer}}/ssf/management/receivers/{{receiverAlias}}
Authorization: Bearer {{keycloakToken}}
Accept: application/json
Content-Type: application/json

{
  "transmitterUrl": "{{transmitterUrl}}",
  "transmitterConfigUrl": "{{transmitterConfigUrl}}",
  "transmitterAccessToken": "{{transmitterToken}}",
  "streamId": "ac974aca-c6e5-494e-bda0-80a470d17dd9",
  "managedStream": false
}


### Register receiver with managed stream (PUSH)
PUT {{issuer}}/ssf/management/receivers/{{receiverAlias}}
Authorization: Bearer {{keycloakToken}}
Accept: application/json
Content-Type: application/json

{
  "description": "Keycloak Demo Receiver with Push",
  "transmitterUrl": "{{transmitterUrl}}",
  "transmitterConfigUrl": "{{transmitterConfigUrl}}",
  "transmitterAccessToken": "{{transmitterToken}}",
  "deliveryMethod": "urn:ietf:rfc:8935",
  "managedStream": true,
  "eventsRequested": [
    "https://schemas.openid.net/secevent/caep/event-type/session-revoked",
    "https://schemas.openid.net/secevent/caep/event-type/token-claims-change",
    "https://schemas.openid.net/secevent/caep/event-type/assurance-level-change",
    "https://schemas.openid.net/secevent/caep/event-type/device-compliance-change",
    "https://schemas.openid.net/secevent/caep/event-type/credential-change"
  ],
  "pushAuthorizationToken": "{{pushToken}}"
}


### Remove receiver
DELETE {{issuer}}/ssf/management/receivers/{{receiverAlias}}
Authorization: Bearer {{keycloakToken}}
Accept: application/json

### Refresh receiver
POST {{issuer}}/ssf/management/receivers/{{receiverAlias}}/refresh
Authorization: Bearer {{keycloakToken}}
Accept: application/json

### Trigger verification
POST {{issuer}}/ssf/management/receivers/{{receiverAlias}}/verify
Authorization: Bearer {{keycloakToken}}
Accept: application/json
