### Push caep.dev session revoked event
POST {{issuer}}/ssf/push/{{caepAlias}}
Authorization: Bearer dummyPushToken
Accept: application/json
Content-Type: application/secevent+jwt


eyJhbGciOiJSUzI1NiIsImtpZCI6IjllMjJlMjc2LWQzYTQtNGE2OS1hZDA4LWQyNmNmNWI0Y2ExOSIsInR5cCI6InNlY2V2ZW50K2p3dCJ9.eyJhdWQiOiJodHRwczovL3Rkd29ya3Nob3BzLm5ncm9rLmRldi9hdXRoL3JlYWxtcy9zc2YtZGVtbyIsImV2ZW50cyI6eyJodHRwczovL3NjaGVtYXMub3BlbmlkLm5ldC9zZWNldmVudC9jYWVwL2V2ZW50LXR5cGUvc2Vzc2lvbi1yZXZva2VkIjp7ImV2ZW50X3RpbWVzdGFtcCI6MTczODYyMTQzOCwic3ViamVjdCI6eyJlbWFpbCI6InRlc3RlckBsb2NhbC50ZXN0IiwiZm9ybWF0IjoiZW1haWwifX19LCJpYXQiOjE3Mzg2MjE0MzgsImlzcyI6Imh0dHBzOi8vc3NmLmNhZXAuZGV2LyIsImp0aSI6IlkyWmxaV05tWmpjdFpXRmlNUzAwT0RRMUxXSTJNMlF0TVRjeFlqY3pNMkppT1RjMCIsInN1Yl9pZCI6eyJlbWFpbCI6InRlc3RlckBsb2NhbC50ZXN0IiwiZm9ybWF0IjoiZW1haWwifX0.Xy71Z-jdELCbXFWAzaTb298XtRCQCZhyFX8qp9DXLYGBbQet6k-xbZDAz5B8CtlapMf5ogBAb7nGep-Gs0L1T-KfdtkTpCLYKrfsStBnmeB1b7sXrshLtEsqhTvL_3CtQHOPUewGAp0z9wMH_M23b4ldzTQDnDYwx6oPiyS2TQt3G_k8R0FnmOhqLs9o3RLW1rvSdPdxkmVnxu9mK56CfT8A7EZCC--aqWwCC4lqj_kizC8sp1C2ezjohrhkkZvz3lvQUh2O9Ij81E_bWOZf4cvvfwegL8yTl96z7tVKH1DS1rO9R4w4WyiMFLMeXWa_3vwpK5g6QSpMdFtqRR2nIg

### Push broken event
POST {{issuer}}/ssf/push/{{caepAlias}}
Authorization: Bearer dummyPushToken
Accept: application/json
Content-Type: application/secevent+jwt

invalidSetJwt


### Push broken event
POST {{issuer}}/ssf/push/{{caepAlias}}
Authorization: Bearer invalidAuth
Accept: application/json
Content-Type: application/secevent+jwt

eyJhbGciOiJSUzI1NiIsImtpZCI6IjllMjJlMjc2LWQzYTQtNGE2OS1hZDA4LWQyNmNmNWI0Y2ExOSIsInR5cCI6InNlY2V2ZW50K2p3dCJ9.eyJhdWQiOiJodHRwczovL3Rkd29ya3Nob3BzLm5ncm9rLmRldi9hdXRoL3JlYWxtcy9zc2YtZGVtbyIsImV2ZW50cyI6eyJodHRwczovL3NjaGVtYXMub3BlbmlkLm5ldC9zZWNldmVudC9jYWVwL2V2ZW50LXR5cGUvc2Vzc2lvbi1yZXZva2VkIjp7ImV2ZW50X3RpbWVzdGFtcCI6MTczODYyMTQzOCwic3ViamVjdCI6eyJlbWFpbCI6InRlc3RlckBsb2NhbC50ZXN0IiwiZm9ybWF0IjoiZW1haWwifX19LCJpYXQiOjE3Mzg2MjE0MzgsImlzcyI6Imh0dHBzOi8vc3NmLmNhZXAuZGV2LyIsImp0aSI6IlkyWmxaV05tWmpjdFpXRmlNUzAwT0RRMUxXSTJNMlF0TVRjeFlqY3pNMkppT1RjMCIsInN1Yl9pZCI6eyJlbWFpbCI6InRlc3RlckBsb2NhbC50ZXN0IiwiZm9ybWF0IjoiZW1haWwifX0.Xy71Z-jdELCbXFWAzaTb298XtRCQCZhyFX8qp9DXLYGBbQet6k-xbZDAz5B8CtlapMf5ogBAb7nGep-Gs0L1T-KfdtkTpCLYKrfsStBnmeB1b7sXrshLtEsqhTvL_3CtQHOPUewGAp0z9wMH_M23b4ldzTQDnDYwx6oPiyS2TQt3G_k8R0FnmOhqLs9o3RLW1rvSdPdxkmVnxu9mK56CfT8A7EZCC--aqWwCC4lqj_kizC8sp1C2ezjohrhkkZvz3lvQUh2O9Ij81E_bWOZf4cvvfwegL8yTl96z7tVKH1DS1rO9R4w4WyiMFLMeXWa_3vwpK5g6QSpMdFtqRR2nIg
